### ISSUE TITLE
Setting Chef version for installation fails

### ISSUE THREAD

**Issue by luckymike** [opscode-cookbooks/chef-server-ingredient#7]
Using the newest Chef Server cookbook, setting node['chef-server']['version'] results in the following error. It works fine if that attribute is unset:

```
54.189.94.51     ================================================================================
54.189.94.51     Error executing action `install` on resource 'chef_server_ingredient[chef-server-core]'
54.189.94.51     ================================================================================
54.189.94.51     
54.189.94.51     Mixlib::ShellOut::ShellCommandFailed
54.189.94.51     ------------------------------------
54.189.94.51     apt_package[chef-server-core] (/var/chef/cookbooks/chef-server-ingredient/libraries/chef_server_ingredients_provider.rb line 48) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
54.189.94.51     ---- Begin output of apt-get -q -y install chef-server-core=12.0.4 ----
54.189.94.51     STDOUT: Reading package lists...
54.189.94.51     Building dependency tree...
54.189.94.51     Reading state information...
54.189.94.51     STDERR: E: Version '12.0.4' for 'chef-server-core' was not found
54.189.94.51     ---- End output of apt-get -q -y install chef-server-core=12.0.4 ----
54.189.94.51     Ran apt-get -q -y install chef-server-core=12.0.4 returned 100
54.189.94.51     
54.189.94.51     Resource Declaration:
54.189.94.51     ---------------------
54.189.94.51     # In /var/chef/cookbooks/chef-server/recipes/default.rb
54.189.94.51     
54.189.94.51      18: chef_server_ingredient 'chef-server-core' do
54.189.94.51      19:   version node['chef-server']['version']
54.189.94.51      20:   notifies :reconfigure, 'chef_server_ingredient[chef-server-core]'
54.189.94.51      21: end
54.189.94.51      22: 
54.189.94.51     
54.189.94.51     Compiled Resource:
54.189.94.51     ------------------
54.189.94.51     # Declared in /var/chef/cookbooks/chef-server/recipes/default.rb:18:in `from_file'
54.189.94.51     
54.189.94.51     chef_server_ingredient("chef-server-core") do
54.189.94.51       action :install
54.189.94.51       updated true
54.189.94.51       updated_by_last_action true
54.189.94.51       retries 0
54.189.94.51       retry_delay 2
54.189.94.51       default_guard_interpreter :default
54.189.94.51       declared_type :chef_server_ingredient
54.189.94.51       cookbook_name :"chef-server"
54.189.94.51       recipe_name "default"
54.189.94.51       version "12.0.4"
54.189.94.51       package_name "chef-server-core"
54.189.94.51     end
```

**Comment by jtimberman** [comment]
It is likely that the older version isn't available in the apt repo when the new version was released.

**Comment by luckymike** [comment]
Naw, fails with the latest specified too:
```
54.185.228.231     ================================================================================
54.185.228.231     Error executing action `install` on resource 'chef_server_ingredient[chef-server-core]'
54.185.228.231     ================================================================================
54.185.228.231     
54.185.228.231     Mixlib::ShellOut::ShellCommandFailed
54.185.228.231     ------------------------------------
54.185.228.231     apt_package[chef-server-core] (/var/chef/cookbooks/chef-server-ingredient/libraries/chef_server_ingredients_provider.rb line 48) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
54.185.228.231     ---- Begin output of apt-get -q -y install chef-server-core=12.0.5 ----
54.185.228.231     STDOUT: Reading package lists...
54.185.228.231     Building dependency tree...
54.185.228.231     Reading state information...
54.185.228.231     STDERR: E: Version '12.0.5' for 'chef-server-core' was not found
54.185.228.231     ---- End output of apt-get -q -y install chef-server-core=12.0.5 ----
54.185.228.231     Ran apt-get -q -y install chef-server-core=12.0.5 returned 100
54.185.228.231     
54.185.228.231     Resource Declaration:
54.185.228.231     ---------------------
54.185.228.231     # In /var/chef/cookbooks/chef-server/recipes/default.rb
54.185.228.231     
54.185.228.231      18: chef_server_ingredient 'chef-server-core' do
54.185.228.231      19:   version node['chef-server']['version']
54.185.228.231      20:   notifies :reconfigure, 'chef_server_ingredient[chef-server-core]'
54.185.228.231      21: end
54.185.228.231      22: 
54.185.228.231     
54.185.228.231     Compiled Resource:
54.185.228.231     ------------------
54.185.228.231     # Declared in /var/chef/cookbooks/chef-server/recipes/default.rb:18:in `from_file'
54.185.228.231     
54.185.228.231     chef_server_ingredient("chef-server-core") do
54.185.228.231       action :install
54.185.228.231       updated true
54.185.228.231       updated_by_last_action true
54.185.228.231       retries 0
54.185.228.231       retry_delay 2
54.185.228.231       default_guard_interpreter :default
54.185.228.231       declared_type :chef_server_ingredient
54.185.228.231       cookbook_name :"chef-server"
54.185.228.231       recipe_name "default"
54.185.228.231       version "12.0.5"
54.185.228.231       package_name "chef-server-core"
54.185.228.231     end
54.185.228.231     
54.185.228.231 
54.185.228.231 Running handlers:
54.185.228.231 [2015-02-28T01:47:21+00:00] ERROR: Running exception handlers
54.185.228.231 Running handlers complete
54.185.228.231 [2015-02-28T01:47:21+00:00] ERROR: Exception handlers complete
54.185.228.231 [2015-02-28T01:47:21+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
54.185.228.231 Chef Client failed. 4 resources updated in 10.141674912 seconds
54.185.228.231 [2015-02-28T01:47:21+00:00] ERROR: chef_server_ingredient[chef-server-core] (chef-server::default line 18) had an error: Mixlib::ShellOut::ShellCommandFailed: apt_package[chef-server-core] (/var/chef/cookbooks/chef-server-ingredient/libraries/chef_server_ingredients_provider.rb line 48) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
54.185.228.231 ---- Begin output of apt-get -q -y install chef-server-core=12.0.5 ----
54.185.228.231 STDOUT: Reading package lists...
54.185.228.231 Building dependency tree...
54.185.228.231 Reading state information...
54.185.228.231 STDERR: E: Version '12.0.5' for 'chef-server-core' was not found
54.185.228.231 ---- End output of apt-get -q -y install chef-server-core=12.0.5 ----
54.185.228.231 Ran apt-get -q -y install chef-server-core=12.0.5 returned 100
54.185.228.231 [2015-02-28T01:47:21+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by jtimberman** [comment]
Okay, what platform and version? We only publish debs in the Package Cloud apt repository for Ubuntu LTS: 10.04, 12.04, 14.04. Those are the only supported platforms for the `chef_server_ingredient` resource. 

Default suite in Test Kitchen passes - here's the serverspec output from 14.04, for example:

```
       chef-server-ingredient::default
         Package "chef-server-core"
           should be installed
         Command "chef-server-ctl test"
           exit_status
             should eq 0
         Package "opscode-manage"
           should be installed
         Command "opscode-manage-ctl test"
           exit_status
             should eq 0

       Finished in 1 minute 42.29 seconds (files took 0.29976 seconds to load)
       4 examples, 0 failures

       Finished verifying <default-ubuntu-1404> (2m25.29s).
```

And the override version suite for 14.04:

```
           * apt_package[chef-server-core] action install
             - install version 12.0.4-1 of package chef-server-core
... serverspec:
       chef-server-ingredient::default
         Package "chef-server-core"
           should be installed

       Finished in 0.11892 seconds (files took 0.32029 seconds to load)
       1 example, 0 failures
```

**Comment by luckymike** [comment]
I ran it with both Ubuntu 12.04 and 14.04 on AWS. It failed with chef-server versions 12.0.3-12.0.5. With no version specified, it succeeds.

--
Michael F. Weinberg | Director of Operations
http://heavywaterops.com | @heavywaterops

**Comment by luckymike** [comment]
So, I tried "12.0.4-1" and it worked. 

Is this a packagecloud bug, it seems like in the absence of a specified patch, one should get the latest? 

The Chef Server install page lists versions as 12.0.x, so anyone attempting to find version numbers is going to be bit by this.

**Comment by jtimberman** [comment]
No, this is because of how Chef internally uses versions in apt repositories.

When Chef manages a package resource, it first loads the current resource. That is, it checks the state of the system to determine if it needs to modify the package based on the action. If the action is `:install`, it will install the package if the current version is nil (package not installed). If the action is `:upgrade`, it will install the candidate version if it does not match the current version (or if the current version is nil).

What this means in practical terms, as we can observe from chef-shell:

```
chef:recipe > p = package("vim")
 => <apt_package[vim] @name: "vim" @noop: nil @before: nil @params: {} @provider: nil @allowed_actions: [:nothing, :install, :upgrade, :remove, :purge, :reconfig] @action: :install @updated: false @updated_by_last_action: false @supports: {} @ignore_failure: false @retries: 0 @retry_delay: 2 @source_line: "(irb#1):1:in `irb_binding'" @guard_interpreter: nil @default_guard_interpreter: :default @elapsed_time: 0 @sensitive: false @candidate_version: nil @options: nil @package_name: "vim" @resource_name: :apt_package @response_file: nil @response_file_variables: {} @source: nil @version: nil @timeout: 900 @default_release: nil @declared_type: :package @cookbook_name: nil @recipe_name: nil>
chef:recipe > run_chef
[2015-03-02T22:56:53-07:00] INFO: Processing apt_package[vim] action install ((irb#1) line 1)
[2015-03-02T22:56:53-07:00] DEBUG: providers for generic apt_package resource enabled on node include: [Chef::Provider::Package::Apt]
[2015-03-02T22:56:53-07:00] DEBUG: providers that refused resource apt_package[vim] were: []
[2015-03-02T22:56:53-07:00] DEBUG: providers that support resource apt_package[vim] include: [Chef::Provider::Package::Apt]
[2015-03-02T22:56:53-07:00] DEBUG: providers that survived replacement include: [Chef::Provider::Package::Apt]
vim:
  Installed: 2:7.4.052-1ubuntu3
  Candidate: 2:7.4.052-1ubuntu3
  Version table:
 *** 2:7.4.052-1ubuntu3 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
[2015-03-02T22:56:53-07:00] DEBUG: apt_package[vim] current version is 2:7.4.052-1ubuntu3
[2015-03-02T22:56:53-07:00] DEBUG: apt_package[vim] candidate version is 2:7.4.052-1ubuntu3
[2015-03-02T22:56:53-07:00] DEBUG: apt_package[vim] vim 2:7.4.052-1ubuntu3 already installed
[2015-03-02T22:56:53-07:00] DEBUG: apt_package[vim] is already installed - nothing to do
```

Notice the versions in the output have the `-1ubuntu3`. This is the revision identifier for the package, similar to `chef-server-core`'s `-1` in `12.0.4-1`. This is the complete version and is required on the package resource. Modifying the `chef_server_ingredient` resource to accommodate that is not appropriate. I think we should stick to the same version string used by Chef's `package` resource, since that is what is being used by `chef_server_ingredient`.
